# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: uquake.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'uquake.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cuquake.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe7\x01\n\x06OneBit\x12\x10\n\x08networks\x18\x01 \x03(\t\x12\x10\n\x08stations\x18\x02 \x03(\t\x12\x11\n\tlocations\x18\x03 \x03(\t\x12\x10\n\x08\x63hannels\x18\x04 \x03(\t\x12\x16\n\x0esampling_rates\x18\x05 \x03(\x05\x12.\n\nstarttimes\x18\x06 \x03(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65ndtimes\x18\x07 \x03(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08nsamples\x18\x08 \x03(\x05\x12\x0c\n\x04\x64\x61ta\x18\t \x03(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'uquake_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ONEBIT']._serialized_start=50
  _globals['_ONEBIT']._serialized_end=281
# @@protoc_insertion_point(module_scope)
